CREATE TABLE IF NOT EXISTS artist (
    artist_id INTEGER PRIMARY KEY NOT NULL,
    artist_name TEXT NOT NULL COLLATE NOCASE,
    extra JSON NOT NULL,
    created_date INTEGER NOT NULL,
    UNIQUE (artist_name COLLATE NOCASE)
)